# config/vite.yml

dev_server:
  host: "localhost"            # Localhost for development, change if necessary
  port: 3000                   # The port where the Vite dev server will run (default 3000)
  hmr: true                    # Enable Hot Module Replacement (HMR) for fast updates during development
  proxy:
    '/rails/active_storage': 'http://localhost:3000'  # Proxy Rails Active Storage requests to Vite

build:
  output_dir: "public"          # Vite build output folder (Rails' public folder)
  assets_dir: "assets"          # Where JS, CSS, images, etc., are placed within the public folder (public/assets)
  manifest: "public/vite/manifest.json"  # Location of the manifest file
  sourcemap: false              # Optional: Set to true if you need source maps for production

asset_host: "https://tester-rxuy.onrender.com"  # URL where assets will be served from during development (adjust for production)

# To enable cache busting and proper file reference, you might want to use an asset host like a CDN in production.
# asset_host: "https://your-cdn-url.com"
